apiVersion: v1
kind: ConfigMap
metadata:
  name: model-signing-pub
  namespace: akili-prod
data:
  pub.pem: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAnB7HNGwO0sUk1Q6jgepSwbdivPZ1mhA+8T+mpr/rSJA=
    -----END PUBLIC KEY-----
