apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: akili-dev
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.memory: 3Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: akili-staging
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: akili-prod
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.memory: 3Gi
