apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MaicyMxtim/akili.git
    targetRevision: main
    path: platform/k8s/pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
