apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MaicyMxtim/akili.git
    targetRevision: main
    path: platform/k8s/serving
  destination:
    server: https://kubernetes.default.svc
    namespace: akili-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
